/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar un mensaje al agente */
        post: operations["postChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de una conversación */
        get: operations["getConversationMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cgm/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forzar un pull a Nightscout ahora */
        post: operations["syncCgm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cgm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de la fuente de lecturas */
        get: operations["getCgmStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cgm/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serie de lecturas para gráficos */
        get: operations["getReadings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cgm/readings/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lecturas manuales */
        post: operations["postReadingsBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cgm/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subir un CSV de LibreView (respaldo e historial) */
        post: operations["postImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cgm/imports/{batchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de un lote */
        get: operations["getImport"];
        put?: never;
        post?: never;
        /** Revertir un lote completo */
        delete: operations["revertImport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Línea de tiempo */
        get: operations["listEvents"];
        put?: never;
        /** Alta estructurada sin chat */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un evento */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        /** Borrado lógico */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /** Corrección */
        patch: operations["patchEvent"];
        trace?: never;
    };
    "/events/{eventId}/glycemic-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Respuesta glucémica de una comida */
        get: operations["getGlycemicResponse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}/glycemic-response/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forzar recálculo */
        post: operations["recomputeGlycemicResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen diario para la pantalla de inicio */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar perfil */
        patch: operations["patchProfile"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        EventType: "MEAL" | "ACTIVITY" | "SLEEP" | "STRESS" | "MEDICATION" | "ALCOHOL" | "SYMPTOM" | "NOTE";
        /** @enum {string} */
        MealType: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK";
        /** @enum {string} */
        TimeConfidence: "EXACT" | "APPROX" | "INFERRED";
        /** @enum {string} */
        Quality: "GOOD" | "PARTIAL" | "CONFOUNDED" | "INSUFFICIENT";
        /** @enum {string} */
        SeriesSource: "REALTIME" | "HISTORIC";
        /** @enum {string} */
        ReadingType: "HISTORIC" | "SCAN" | "REALTIME" | "MANUAL" | "STRIP";
        /** @enum {string} */
        MacroSource: "CATALOG" | "USER_ALIAS" | "LLM_FALLBACK" | "LABEL";
        /** @description Punto más intervalo plausible (diseño 10.1) */
        Range: {
            point: number;
            low: number;
            high: number;
        };
        EventTime: {
            /** Format: date-time */
            at: string;
            /** @example America/Mexico_City */
            localTz: string;
            confidence: components["schemas"]["TimeConfidence"];
            uncertaintyMin: number;
            basis?: string | null;
        };
        ChatRequest: {
            /** Format: uuid */
            conversationId?: string | null;
            /**
             * Format: uuid
             * @description Lo genera el cliente; un reintento con el mismo id devuelve la respuesta guardada
             */
            clientMessageId: string;
            text: string;
            /** Format: date-time */
            clientTime: string;
            timezone: string;
        };
        ChatResponse: {
            /** Format: uuid */
            conversationId: string;
            reply: string;
            createdEvents: components["schemas"]["EventSummary"][];
            updatedEvents: components["schemas"]["EventSummary"][];
            clarification?: string | null;
            dataQualityNotes: string[];
        };
        ChatMessage: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "USER" | "ASSISTANT" | "TOOL";
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        SyncResult: {
            sourceReachable: boolean;
            newReadings: number;
            /** Format: date-time */
            latestReadingTs?: string | null;
            elapsedMs: number;
        };
        CgmStatus: {
            /** @example NIGHTSCOUT */
            source: string;
            /** Format: date-time */
            lastPullAt?: string | null;
            /** Format: date-time */
            lastReadingTs?: string | null;
            minutesSinceLastReading?: number | null;
            lastStatus?: string | null;
            lastError?: string | null;
            consecutiveFailures: number;
        };
        Reading: {
            /** Format: date-time */
            ts: string;
            mgdl: number;
            type: components["schemas"]["ReadingType"];
            clipped: boolean;
        };
        GridPoint: {
            /** Format: date-time */
            ts: string;
            mgdl: number;
            observed: boolean;
        };
        ReadingsResponse: {
            /** @enum {string} */
            resolution: "raw" | "5m";
            readings?: components["schemas"]["Reading"][];
            grid?: components["schemas"]["GridPoint"][];
        };
        ReadingInput: {
            /**
             * Format: date-time
             * @description ISO-8601 con offset
             */
            ts: string;
            value: number;
            /** @enum {string} */
            unit: "MG_DL" | "MMOL_L";
            type?: components["schemas"]["ReadingType"];
        };
        ImportBatch: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            source: "LIBREVIEW_CSV" | "MANUAL";
            sourceName?: string | null;
            assumedTimezone?: string | null;
            detectedCadenceSec?: number | null;
            /** @enum {string} */
            status: "RECEIVED" | "STORED" | "REVERTED" | "FAILED";
            rowsTotal?: number | null;
            rowsInserted?: number | null;
            rowsDuplicate?: number | null;
            rowsRejected?: number | null;
            /** Format: date-time */
            rangeStart?: string | null;
            /** Format: date-time */
            rangeEnd?: string | null;
            warnings?: {
                [key: string]: unknown;
            }[];
            error?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        EventSummary: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["EventType"];
            time: components["schemas"]["EventTime"];
            /** Format: date-time */
            endedAt?: string | null;
            rawText?: string | null;
            meal?: components["schemas"]["MealSummaryView"];
        };
        MealSummaryView: {
            mealType: components["schemas"]["MealType"];
            carbsG: number;
            carbsBand: components["schemas"]["Range"];
            confidence: number;
            foods?: string[];
            quality?: components["schemas"]["Quality"];
            deltaPeakMgdl?: number | null;
            inProgress?: boolean;
        };
        EventDetail: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["EventType"];
            time: components["schemas"]["EventTime"];
            /** Format: date-time */
            endedAt?: string | null;
            source: string;
            rawText?: string | null;
            /** Format: uuid */
            messageId?: string | null;
            attributes: {
                [key: string]: unknown;
            };
            meal?: components["schemas"]["MealDetail"];
            /** Format: date-time */
            createdAt: string;
        };
        MealDetail: {
            mealType: components["schemas"]["MealType"];
            items: components["schemas"]["MealItemDetail"][];
            totals: components["schemas"]["Nutrients"];
            carbsBand: components["schemas"]["Range"];
            carbsWorstCase: components["schemas"]["Range"];
            confidence: number;
            estimatorVersion: string;
            clarificationQuestion?: string | null;
        };
        /** @description Lo que muestra el cajón "¿por qué este número?" (diseño 10.5) */
        MealItemDetail: {
            raw: string;
            foodName: string;
            preparation?: string | null;
            /** Format: uuid */
            foodRefId?: string | null;
            quantity?: number | null;
            unit?: string | null;
            grams: components["schemas"]["Range"];
            volumeMl?: number | null;
            portionEaten: number;
            nutrients: components["schemas"]["Nutrients"];
            carbsRange: components["schemas"]["Range"];
            confidence: number;
            llmConfidence?: number | null;
            macroSource: components["schemas"]["MacroSource"];
            assumptions: string[];
            needsClarification: boolean;
        };
        Nutrients: {
            /** @description hidratos disponibles */
            carbsG: number;
            fiberG: number;
            proteinG: number;
            fatG: number;
            kcal: number;
        };
        NewEventInput: {
            type: components["schemas"]["EventType"];
            time: components["schemas"]["EventTime"];
            /** Format: date-time */
            endedAt?: string | null;
            rawText?: string | null;
            attributes?: {
                [key: string]: unknown;
            };
            meal?: components["schemas"]["MealInput"];
        };
        /** @description Comida ya extraída (mismo esquema que la tool log_events, diseño 8.4); la estima el servidor */
        MealInput: {
            mealType: components["schemas"]["MealType"];
            repeatOfEventRef?: string | null;
            items: components["schemas"]["ExtractedItemInput"][];
        };
        ExtractedItemInput: {
            raw: string;
            food: string;
            preparation?: string | null;
            brand?: string | null;
            quantity?: number | null;
            unit?: string | null;
            grams?: components["schemas"]["Range"];
            volumeMl?: number | null;
            /** @default 1 */
            portionEaten: number;
            assumptions?: string[];
        };
        EventPatchInput: {
            time?: components["schemas"]["EventTime"];
            /** Format: date-time */
            endedAt?: string | null;
            attributes?: {
                [key: string]: unknown;
            } | null;
            meal?: components["schemas"]["MealInput"];
        };
        GlycemicResponseView: {
            /** Format: uuid */
            mealEventId: string;
            algorithmVersion: string;
            /** Format: date-time */
            computedAt: string;
            seriesSource: components["schemas"]["SeriesSource"];
            cadenceSec: number;
            scanFraction?: number | null;
            quality: components["schemas"]["Quality"];
            coveragePct: number;
            maxGapMin?: number | null;
            baselineMgdl?: number | null;
            baselineN?: number;
            baselineUnstable?: boolean;
            peakMgdl?: number | null;
            /** Format: date-time */
            peakAt?: string | null;
            timeToPeakMin?: number | null;
            deltaPeakMgdl?: number | null;
            g30?: number | null;
            g60?: number | null;
            g90?: number | null;
            g120?: number | null;
            g180?: number | null;
            returnToBaselineMin?: number | null;
            iauc0to120?: number | null;
            iauc0to180?: number | null;
            maxRiseRate?: number | null;
            maxFallRate?: number | null;
            minutesAbovePersonalP90?: number | null;
            personalP90Mgdl?: number | null;
            /** Format: date-time */
            windowEnd?: string | null;
            flags: string[];
            contextTags: string[];
            /** @description Rejilla de 5 min desde −60 hasta el fin de la ventana, para dibujar */
            curve: components["schemas"]["GridPoint"][];
        };
        GlucoseSummary: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            personalRange?: components["schemas"]["PersonalRange"];
            days: components["schemas"]["DailyStats"][];
        };
        PersonalRange: {
            p10Mgdl?: number | null;
            p50Mgdl?: number | null;
            p90Mgdl?: number | null;
            /** Format: date */
            periodEnd: string;
            windowDays: number;
            readingsCount: number;
        };
        DailyStats: {
            /** Format: date */
            day: string;
            meanMgdl?: number | null;
            p10Mgdl?: number | null;
            p50Mgdl?: number | null;
            p90Mgdl?: number | null;
            minutesAbovePersonalP90: number;
            coveragePct: number;
            mealsLogged: number;
        };
        Profile: {
            displayName: string | null;
            timezone: string;
            /** @enum {string} */
            glucoseUnit: "MG_DL" | "MMOL_L";
            locale: string;
            preferences: {
                [key: string]: unknown;
            };
        };
        ProfilePatch: {
            displayName?: string | null;
            timezone?: string | null;
            /** @enum {string|null} */
            glucoseUnit?: "MG_DL" | "MMOL_L" | null;
            preferences?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Respuesta del agente y eventos creados o actualizados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
        };
    };
    getConversationMessages: {
        parameters: {
            query?: {
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mensajes, del más antiguo al más reciente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
        };
    };
    syncCgm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado del pull; sourceReachable=false si Nightscout no respondió */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
        };
    };
    getCgmStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Último pull, última lectura, fallos consecutivos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CgmStatus"];
                };
            };
        };
    };
    getReadings: {
        parameters: {
            query: {
                from: string;
                to: string;
                /** @description raw limitado a 31 días */
                resolution?: "raw" | "5m";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecturas o rejilla de 5 min con marca observado/interpolado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingsResponse"];
                };
            };
        };
    };
    postReadingsBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingInput"][];
            };
        };
        responses: {
            /** @description Lecturas insertadas y duplicadas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
        };
    };
    postImport: {
        parameters: {
            query?: {
                /** @description Zona asumida para las horas locales del CSV; por defecto la del usuario */
                timezone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Lote procesado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
            /** @description Lote grande; se procesa en segundo plano */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
        };
    };
    getImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
        };
    };
    revertImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lote revertido; se recomputan las comidas afectadas */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEvents: {
        parameters: {
            query: {
                from: string;
                to: string;
                type?: components["schemas"]["EventType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eventos con resumen de comida y calidad de su respuesta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"][];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewEventInput"];
            };
        };
        responses: {
            /** @description Evento creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comida con ítems, rangos, supuestos y fuente de cada macro */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description No existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Borrado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPatchInput"];
            };
        };
        responses: {
            /** @description Evento actualizado; dispara reestimación y recomputación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    getGlycemicResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Métricas y puntos de la curva para dibujar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlycemicResponseView"];
                };
            };
            /** @description Aún no calculada o el evento no es una comida */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recomputeGlycemicResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recálculo encolado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSummary: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estadísticos por día y rango personal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlucoseSummary"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    patchProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Perfil actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
}
